var locCollection = [
	{id: "1",
	name: "Roma Norte",
	coords: {lat: 19.417910, lng: -99.161575},
	visible: true,
	wikiName: "Colonia Roma",
	keywords: ["roma", "norte", "colonia", "cuauhtémoc", "cuauhtemoc"],
	icon: "icons/home.png"},
	
	{id: "2",
	name: "Chapultepec",
	coords: {lat: 19.419851, lng: -99.186111},
	visible: true,
	wikiName: "Chapultepec",
	keywords: ["chapultepec", "bosque", "forest", "park"],
	icon: "icons/park.png"},
	
	{id: "3",
	name: "Arena México",
	coords: {lat: 19.424507, lng: -99.152091},
	visible: true,
	wikiName: "Arena México",
	keywords: ["arena", "lucha", "libre", "wrestling"],
	icon: "icons/wrestling.png"},
	
	{id: "4",
	name: "National Museum of Anthropology",
	coords: {lat: 19.426001, lng: -99.186462},
	visible: true,
	wikiName: "National Museum of Anthropology (Mexico)",
	keywords: ["museo", "museum", "antropología", "antropologia",
			   "anthropology"],
	icon: "icons/museum.png"},
	
	{id: "5",
	name: "Condesa",
	coords: {lat: 19.415189, lng: -99.175612},
	visible: true,
	wikiName: "Condesa",
	keywords: ["condesa", "colonia", "cuauhtémoc", "cuauhtemoc",
			   "hipódromo", "hipodromo"],
	icon: "icons/condesa.png"},
	
	{id: "6",
	name: "Zócalo",
	coords: {lat: 19.432606, lng: -99.133180},
	visible: true,
	wikiName: "Zócalo",
	keywords: ["zócalo", "zocalo", "plaza", "centro", "center", "centre",
			   "constitución", "constitucion"],
	icon: "icons/plaza.png"},
	
	{id: "7",
	name: "Zona Rosa",
	coords: {lat: 19.425653, lng: -99.163658},
	visible: true,
	wikiName: "Zona Rosa, Mexico City",
	keywords: ["zona", "rosa", "colonia", "juárez", "juarez", "gay",
			   "korean", "korea"],
	icon: "icons/rosa.png"}
];
